FROM node:20-alpine

WORKDIR /app

RUN apk add --no-cache libc6-compat

COPY package*.json ./
COPY turbo.json ./

COPY packages ./packages

COPY apps/web ./apps/web

RUN npm install

EXPOSE 3000

CMD ["npm", "run", "dev", "--workspace=web"]
